### ISSUE TITLE
Assignment 19th dec 

### ISSUE THREAD

**Issue by Jena-Biswajit** [Jena-Biswajit/learning-project-01-learning-tracker-201#6]
- List down Object class methods in md file
- Example to use object class methods like getclass ,hashcode , tostring,equals
- In a employee class override equals and hashcode methiod, tostring method from object class 
- Static and non static block execution (code,md)
- Use of Super constuctor and super keyword to access parent class .

**Comment by rkpatra201** [comment]
@Jena-Biswajit I have updated the assignment for object class methods. You must list down each of the method.

**Comment by Jena-Biswajit** [comment]
@rkpatra201  I have fixed spelling error ,correct the class and variable name . please check and let me know if anything to change .
